
const library = [
    {name: 'Sowing', date: 'August 19 1990', type: 'service', source: 'https://heavenly-treasures.s3.us-east-2.amazonaws.com/8%3D19+90+Lamon+Napper+Sowing+Tent+Revival.mp3'},
    {name: 'Considering His Promises', date: 'February 17 1983', type: 'service', source: 'https://heavenly-treasures.s3.us-east-2.amazonaws.com/9_Considering+His+Promises+021783.mp3'},
    {name: 'Radio Broadcast', date: 'September 20 1981', type: 'radio', source: 'https://heavenly-treasures.s3.us-east-2.amazonaws.com/10_Radio+Broadcast+092081.mp3'},
    {name: 'Radio Broadcast', date: 'October 4 1981', type: 'radio', source: 'https://heavenly-treasures.s3.us-east-2.amazonaws.com/11_Radio+Broadcast+100481.mp3'},
    {name: 'Servant', date: '1987', type: 'service', source: 'https://heavenly-treasures.s3.us-east-2.amazonaws.com/12_Servant_+At+Brother+Carlie\'s+1987.mp3'},
    {name: 'Without Faith', date: 'March 17 1985', type: 'service', source: 'https://heavenly-treasures.s3.us-east-2.amazonaws.com/14_Without+Faith_at+West+Point+031785.mp3'},
    {name: 'Brandenburg', date: 'April 26 1980', type: 'service', source: 'https://heavenly-treasures.s3.us-east-2.amazonaws.com/16_Brandenburg+042680.mp3'},
    {name: 'Leitchfield Tent Revival', date: 'September 20 1986', type: 'service', source: 'https://heavenly-treasures.s3.us-east-2.amazonaws.com/19_Tent+Leitchfield+092086.mp3'},
    {name: 'Mike McKim\'s', date: 'February 19 1983', type: 'service', source: 'https://heavenly-treasures.s3.us-east-2.amazonaws.com/20_Mike+McKim\'s+Church+021983.mp3'},
    {name: 'Decker\'s Church', date: 'May 17 1986', type: 'service', source: 'https://heavenly-treasures.s3.us-east-2.amazonaws.com/21_Decker\'s+Church+051786.mp3'},
    {name: 'ElizabethTown', date: 'September 07 1980', type: 'service', source: 'https://heavenly-treasures.s3.us-east-2.amazonaws.com/22_Etown+090780.mp3'},
    {name: 'Radio Broadcast', date: 'January 11 1981', type: 'radio', source: 'https://heavenly-treasures.s3.us-east-2.amazonaws.com/23-RB+011181.mp3'},
    {name: 'Radio Broadcast', date: 'October 05 1980', type: 'radio', source: 'https://heavenly-treasures.s3.us-east-2.amazonaws.com/24+RB+100580.mp3'},
    {name: 'Radio Broadcast', date: 'November 29 1980', type: 'radio', source: 'https://heavenly-treasures.s3.us-east-2.amazonaws.com/25+RB+112980.mp3'},
    {name: 'Radio Broadcast', date: 'March 28 1982', type: 'radio', source: 'https://heavenly-treasures.s3.us-east-2.amazonaws.com/26++Radio+Broadcast+032882.mp3'},
    {name: 'Radio Broadcast', date: 'July 18 1982', type: 'radio', source: 'https://heavenly-treasures.s3.us-east-2.amazonaws.com/27+RB+071882.mp3'},
    {name: 'Radio Broadcast', date: 'October 18 1981', type: 'radio', source: 'https://heavenly-treasures.s3.us-east-2.amazonaws.com/29+RB++10-18-81.mp3'},
    {name: 'Blessing Curses', date: 'February 26 1983', type: 'service', source: 'https://heavenly-treasures.s3.us-east-2.amazonaws.com/30_Brandenburg_Blessing_Curses_+022683.mp3'},
    {name: 'Radio Broadcast', date:'unknown', type: 'radio', source: 'https://heavenly-treasures.s3.us-east-2.amazonaws.com/31_RB_Jr-Marcia+n+charge_edit+28+min.mp3'},
    {name: 'Radio Broadcast', date: 'July 04 1982', type: 'radio', source: 'https://heavenly-treasures.s3.us-east-2.amazonaws.com/32_RB+070482.mp3'},
    {name: 'Radio Broadcast', date: 'September 12 1982', type: 'radio', source: 'https://heavenly-treasures.s3.us-east-2.amazonaws.com/33_RB+091282.mp3'},
    {name: 'Radio Broadcast', date: 'June 06 1982', type: 'radio', source: 'https://heavenly-treasures.s3.us-east-2.amazonaws.com/34_RB+060682.mp3'},
    {name: 'Radio Broadcast', date: 'August 22 1982', type: 'radio', source: 'https://heavenly-treasures.s3.us-east-2.amazonaws.com/35_RB+082282.mp3'},
    {name: 'Children of Israel', date: 'March 27 1983', type: 'service', source: 'https://heavenly-treasures.s3.us-east-2.amazonaws.com/36_Children+of+Israel_Brandenburg+032783.mp3'},
    {name: 'Jenkins Tent Revival', date: 'August 01 1980', type: 'service', source: 'https://heavenly-treasures.s3.us-east-2.amazonaws.com/37_Tent+at+Bro+Jenkins+080180.mp3'},
    {name: 'Lamon Napper Sr.', date: 'unknown', type: 'service', source: 'https://heavenly-treasures.s3.us-east-2.amazonaws.com/38_Lamon.mp3'},
    {name: 'Cane Run Road', date: 'May 28 1987', type: 'service', source: 'https://heavenly-treasures.s3.us-east-2.amazonaws.com/39_Louisville+Cane+Run+Road+052887.mp3'},
    {name: 'Radio Broadcast', date: 'July 11 1982', type: 'radio', source: 'https://heavenly-treasures.s3.us-east-2.amazonaws.com/40_RB+071182.mp3'},
    {name: 'Radio Broadcast', date: 'September 19 1982', type: 'radio', source: 'https://heavenly-treasures.s3.us-east-2.amazonaws.com/41_+RB+091982.mp3'},
    {name: 'Radio Broadcast', date: 'June 27 1982', type: 'radio', source: 'https://heavenly-treasures.s3.us-east-2.amazonaws.com/42RB-06-27-82.mp3'},
    {name: 'Radio Broadcast', date: 'May 23 1982', type: 'radio', source: 'https://heavenly-treasures.s3.us-east-2.amazonaws.com/43+_+RB+052382.mp3'},
    {name: 'Radio Broadcast', date: 'April 11 1982', type: 'radio', source: 'https://heavenly-treasures.s3.us-east-2.amazonaws.com/44_RB+041182.mp3'},
    {name: 'Radio Broadcast', date: 'May 16 1982', type: 'radio', source: 'https://heavenly-treasures.s3.us-east-2.amazonaws.com/45_RB_051682.mp3'},
    {name: 'Radio Broadcast', date: 'February 21 1982', type: 'radio', source: 'https://heavenly-treasures.s3.us-east-2.amazonaws.com/46_RB_022182.mp3'},
    {name: 'Cane Run Road', date: 'May 1987', type: 'service', source: 'https://heavenly-treasures.s3.us-east-2.amazonaws.com/48-Louisville+Ky+Cane+Run+Road+0587.mp3'},
    {name: 'Radio Broadcast', date: 'March 28 1982', type: 'radio', source: 'https://heavenly-treasures.s3.us-east-2.amazonaws.com/49_RB_032882.mp3'},
    {name: 'Radio Broadcast', date: 'July 18 1982', type: 'radio', source: 'https://heavenly-treasures.s3.us-east-2.amazonaws.com/50_RB_+071882.mp3'},
    {name: 'Campground', date: '1982', type: 'service', source: 'https://heavenly-treasures.s3.us-east-2.amazonaws.com/52_Campground-1982.mp3'},
    {name: 'Bro Pete\'s Church', date: 'October 12 1986', type: 'service', source: 'https://heavenly-treasures.s3.us-east-2.amazonaws.com/55-Bro+Pete\'s+Church+10-12-86.mp3'},
    {name: 'Campground', date: 'July 7 1999', type: 'service', source: 'https://heavenly-treasures.s3.us-east-2.amazonaws.com/56-Campground-07-07-99.mp3'},
    {name: 'Lamon Napper Sr.', date: 'October 31 1987', type: 'service', source: 'https://heavenly-treasures.s3.us-east-2.amazonaws.com/60_Lamon+Napper+103187.mp3'},
    {name: 'Leon Ashley\'s Church', date: 'August 03 1987', type: 'service', source: 'https://heavenly-treasures.s3.us-east-2.amazonaws.com/61_Leon+Ashley\'s+Church++0803087.mp3'},
    {name: 'Campground', date: 'July 17 1998', type: 'service', source: 'https://heavenly-treasures.s3.us-east-2.amazonaws.com/62_Campground+071798.mp3'},
    {name: 'Sheepfold Church', date: 'April 28 1983', type: 'service', source: 'https://heavenly-treasures.s3.us-east-2.amazonaws.com/63_Sheepfold+Church+040283+How+Close.mp3'},
    {name: 'Leitchfield Tent Revival', date: 'June 26 1980', type: 'service', source: 'https://heavenly-treasures.s3.us-east-2.amazonaws.com/64_Tent+Revival+Leitchfield++062680.mp3'},
    {name: 'Have God\'s Nature', date: 'August 4 1985', type: 'service', source: 'https://heavenly-treasures.s3.us-east-2.amazonaws.com/66_Have++God\'s+Nature_Bro+Carlie\'s+080485.mp3'},
    {name: 'Radio Broadcast', date: 'August 29 1982', type: 'radio', source: 'https://heavenly-treasures.s3.us-east-2.amazonaws.com/67_RB+082982.mp3'},
    {name: 'Radio Broadcast', date: 'November 7 1982', type: 'radio', source: 'https://heavenly-treasures.s3.us-east-2.amazonaws.com/68_RB+110782.mp3'},
    {name: 'Radio Broadcast', date: 'May 24 1981', type: 'radio', source: 'https://heavenly-treasures.s3.us-east-2.amazonaws.com/69_RB+052481.mp3'}
]

export {library}